// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type CreateImageMosaicByStoreReq struct {
	ImageName  string `json:"imageName"`
	ImageTitle string `json:"imageTitle"`
	StoreName  string `json:"storeName"`
}

type CreateImageMosaicByStoreResp struct {
	Success bool   `json:"success"`
	Info    string `json:"info"`
}

type CreateImageMosaicReq struct {
	StoreName string `json:"storeName"`
	FilePath  string `json:"filePath"`
}

type CreateImageMosaicResp struct {
	Success bool   `json:"success"`
	Info    string `json:"info"`
}

type CreateImageMosaicStoreReq struct {
	TaskId    string `json:"taskId"`
	BucketUrl string `json:"bucketUrl"`
}

type CreateImageMosaicStoreResp struct {
	Success bool   `json:"success"`
	Info    string `json:"info"`
}

type DelGeoContainerResp struct {
	Success bool   `json:"success"`
	Info    string `json:"info"`
}

type DelImageMosaicReq struct {
	StoreName string `json:"storeName"`
}

type DelImageMosaicResp struct {
	Success bool   `json:"success"`
	Info    string `json:"info"`
}

type StartGeoContainerResp struct {
	Success bool   `json:"success"`
	Info    string `json:"info"`
}

type UploadImageMosaicReq struct {
	UploadZipUrl string `json:"uploadZipUrl"`
	ZipFilePath  string `json:"zipFilePath"`
}

type UploadImageMosaicResp struct {
	Success bool   `json"success"`
	Info    string `json"info"`
}
