// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type CreateImageMosaicByStoreReq struct {
	ImageName  string `json:"imageName"`
	ImageTitle string `json:"imageTitle"`
	StoreName  string `json:"storeName"`
}

type CreateImageMosaicByStoreReqV2 struct {
	TaskId string `json:"taskId"`
}

type CreateImageMosaicByStoreResp struct {
	Success bool   `json:"success"`
	Info    string `json:"into"`
}

type CreateImageMosaicByStoreRespV2 struct {
	Success bool   `json:"success"`
	Info    string `json:"into"`
}

type CreateImageMosaicByZipReq struct {
	StoreName string `json:"storeName"`
	FilePath  string `json:"filePath"`
}

type CreateImageMosaicByZipReqV2 struct {
	UploadZipUrl string `json:"uploadZipUrl"`
	ZipFilePath  string `json:"zipFilePath"`
}

type CreateImageMosaicByZipResp struct {
	Success bool   `json:"success"`
	Info    string `json:"into"`
}

type CreateImageMosaicByZipRespV2 struct {
	Success bool   `json:"success"`
	Info    string `json:"into"`
}

type CreateImageMosaicStoreReq struct {
	TaskId    string `json:"taskId"`
	BucketUrl string `json:"bucketUrl"`
}

type CreateImageMosaicStoreResp struct {
	Success bool   `json:"success"`
	Info    string `json:"into"`
}

type DelGeoContainerResp struct {
	Success bool   `json:"success"`
	Info    string `json:"into"`
}

type DelImageMosaicReq struct {
	ImageName string `json:"imageName"`
	StoreName string `json:"storeName"`
}

type DelImageMosaicReqV2 struct {
	TaskId string `json:"taskId"`
}

type DelImageMosaicStoreReq struct {
	StoreName string `json:"storeName"`
}

type DelImageMosaicStoreReqV2 struct {
	TaskId string `json:"taskId"`
}

type DelImageMosaicStoreResp struct {
	Success bool   `json:"success"`
	Info    string `json:"into"`
}

type DelImageMosaicStoreRespV2 struct {
	Success bool   `json:"success"`
	Info    string `json:"into"`
}

type ErrorResponse struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

type StartGeoContainerResp struct {
	Success bool   `json:"success"`
	Info    string `json:"into"`
}
